# Generated by Django 3.2 on 2021-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to='page_images/')),
                ('page_text', models.CharField(max_length=300)),
            ],
        ),
    ]
